-- Si la tabla ya existe y quieres recrearla con los nuevos datos y la nueva columna, descomenta la siguiente línea:
-- DROP TABLE IF EXISTS public.marketing_projects;

CREATE TABLE public.marketing_projects (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  title text NOT NULL,
  slug text NOT NULL,
  short_description text NOT NULL,
  description text NOT NULL,
  solution text NOT NULL,
  image_url text,
  company_name text NOT NULL, -- Nueva columna
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT marketing_projects_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_projects_slug_key UNIQUE (slug)
);

INSERT INTO public.marketing_projects (title, slug, short_description, description, solution, image_url, company_name) VALUES
('Campaña SEO para E-commerce', 'seo-e-commerce', 'Aumento del tráfico orgánico y conversiones para una tienda online.', 'Una tienda de ropa online necesitaba mejorar su visibilidad en los motores de búsqueda y aumentar sus ventas sin depender exclusivamente de la publicidad pagada. Realizamos un análisis exhaustivo de palabras clave y la competencia.', 'Implementamos una estrategia SEO integral que incluyó optimización on-page (estructura de URL, meta descripciones, contenido de productos), optimización técnica (velocidad de carga, mobile-first) y una campaña de link building de alta calidad. Esto resultó en un aumento del 150% en el tráfico orgánico y un 80% en las conversiones en 6 meses.', '/placeholder.svg?height=400&width=600', 'ModaExpress'),
('Estrategia de Contenido para SaaS B2B', 'contenido-saas-b2b', 'Posicionamiento como líder de pensamiento y generación de leads cualificados.', 'Una empresa de software B2B buscaba establecerse como un referente en su nicho y atraer leads de alta calidad a través de contenido educativo y relevante. Su blog existente tenía poco tráfico y baja interacción.', 'Desarrollamos una estrategia de contenido basada en pilares temáticos, creando artículos de blog, whitepapers y webinars optimizados para SEO y para responder a las preguntas clave de su audiencia. Implementamos un calendario editorial riguroso y promovimos el contenido en redes sociales y email marketing. Logramos un aumento del 300% en el tráfico del blog y un 50% en la generación de leads cualificados.', '/placeholder.svg?height=400&width=600', 'TechSolutions Pro'),
('Relanzamiento de Marca en Redes Sociales', 'relanzamiento-redes', 'Revitalización de la presencia digital y aumento del engagement de la comunidad.', 'Una marca de alimentos con una presencia estancada en redes sociales necesitaba un impulso para conectar con una audiencia más joven y aumentar la interacción con sus publicaciones. Su contenido era genérico y no generaba conversación.', 'Diseñamos una nueva identidad visual y tono de voz para sus redes sociales, enfocándonos en contenido interactivo, historias de usuarios y campañas con influencers. Lanzamos concursos y encuestas para fomentar la participación. El resultado fue un aumento del 400% en el engagement y un crecimiento del 150% en seguidores en 3 meses.', '/placeholder.svg?height=400&width=600', 'SaborAuténtico'),
('Campaña de Google Ads para Servicios Locales', 'google-ads-local', 'Generación de llamadas y visitas a un negocio físico.', 'Un gimnasio local quería atraer más clientes de su área geográfica inmediata. Sus campañas de publicidad anteriores no estaban generando suficientes leads y el costo por clic era muy alto.', 'Creamos y optimizamos campañas de Google Ads enfocadas en la búsqueda local, utilizando palabras clave de cola larga y extensiones de anuncio específicas para la ubicación. Implementamos seguimiento de conversiones para llamadas telefónicas y direcciones. Esto llevó a un aumento del 250% en las llamadas y un 180% en las visitas a la web desde anuncios, con una reducción del 30% en el CPC.', '/placeholder.svg?height=400&width=600', 'FitnessTotal Gym'),
('Automatización de Email Marketing para Retención', 'email-automation', 'Mejora de la retención de clientes y el valor de vida del cliente.', 'Una plataforma de suscripción tenía una alta tasa de abandono después del primer mes. Necesitaban una forma de mantener a los usuarios comprometidos y reducir la rotación.', 'Diseñamos y configuramos una serie de flujos de email marketing automatizados: bienvenida, onboarding, reactivación y cumpleaños. Personalizamos el contenido según el comportamiento del usuario. Esto resultó en una reducción del 20% en la tasa de abandono y un aumento del 15% en las compras repetidas en 4 meses.', '/placeholder.svg?height=400&width=600', 'StreamFlow Plataforma'),
('Desarrollo de Landing Page de Alta Conversión', 'landing-page-conversion', 'Optimización de una página de destino para maximizar las conversiones de una campaña.', 'Una empresa de servicios financieros estaba lanzando un nuevo producto y necesitaba una landing page que convirtiera eficazmente a los visitantes en leads. Su página actual tenía una baja tasa de conversión.', 'Realizamos un análisis de la audiencia y la propuesta de valor para diseñar una landing page con un enfoque claro en la conversión. Implementamos principios de UX/UI, pruebas A/B de titulares y CTAs, y optimización de la velocidad de carga. La nueva landing page logró una tasa de conversión del 12%, superando el objetivo inicial del 5%.', '/placeholder.svg?height=400&width=600', 'Finanzas Inteligentes');
